<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>StreackLib</artifactId>
  <groupId>com.github.streackmc</groupId>
  <version>0.2.0</version>
  <packaging>jar</packaging>
  <description>为StreackMC Team旗下插件提供前置能力</description>

  <properties>
    <maven.compiler.souce>17</maven.compiler.souce>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <paper.version>1.21.8-R0.1-SNAPSHOT</paper.version>
    <spigot.version>1.21.5-R0.1-SNAPSHOT</spigot.version>
  </properties>

  <!-- Repositories -->
  <repositories>
    <repository>
      <id>paper-repo</id>
      <url>https://repo.destroystokyo.com/repository/maven-public/</url>
    </repository>
    <repository>
      <id>spigot-repo</id>
      <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
    </repository>
    <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>
    <repository>
      <id>bstats-repo</id>
      <url>https://repo.codemc.org/repository/maven-public</url>
    </repository>
  </repositories>

  <!-- Dependencies -->
  <dependencies>
    <!-- Basic -->
    <dependency>
      <groupId>org.spigotmc</groupId>
      <artifactId>spigot-api</artifactId>
      <version>${spigot.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>io.papermc.paper</groupId>
      <artifactId>paper-api</artifactId>
      <version>${paper.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>jsr305</artifactId>
      <version>3.0.2</version>
      <scope>provided</scope>
    </dependency>
    <!-- HTTP-Server -->
    <dependency>
      <groupId>org.nanohttpd</groupId>
      <artifactId>nanohttpd</artifactId>
      <version>2.3.1</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.11.0</version>
        <configuration>
          <release>17</release>
        </configuration>
      </plugin>
    </plugins>
    <!-- Resource Path -->
    <resources>
      <resource>
        <directory>${basedir}</directory>
        <includes>
          <include>LICENSE</include>
        </includes>
      </resource>
    </resources>
  </build>
</project>