## 
# # StreackLib配置文件
# 该文件是一个 YAML 类型的配置文件，严格需求缩进。
# 建议使用 YAML 编辑器保证语法正确；若语法错误，所有配置项视作默认值。
# 若值错误，该配置项一般视作默认值。
#
# 注有 * 的配置项表示该配置不支持自动重载，需要重启才能应用更改。
##

## Database
# 本配置节下第一个配置节的名称是“档案名称”，其他应用调用时要传入档案名。每个档案如何设置见下。
databases:
  profile_splite:
    

## Email
# 本配置节下第一个配置节的名称是“档案名称”，其他应用调用时要传入档案名。每个档案如何设置见下。
emails:
  profile_smtp:
    # 发件邮箱
    from: "foo@example.com"
    # 发件人名
    from-who: "Mr.Foo"
    # 若回复，应该回到哪里
    reply-to: "bar@example.com"
    # 本配置的档案名称为[profile_smtp]
    # 每个配置都需要填写下面的工作模式
    mode: "smtp"
    # 对于 SMTP 模式，你需要填写 服务地址、账户密码或者 OAUTH Token
    server: 
    # 一般为 587(STARTTLS) ，部分服务器接受 465(SSL)
    port: 587
    username: 
    password: 
    # 如果你配置了下面的 OAUTH Token ，那么会自动忽略账号密码验证
    oauth-token: 
    # 接受的连接超时时长（ms）
    timeout: 10000
    # 是否使用 TLS 确保安全连接
    tls: true
  profile_selfsign:
    from: "foo@example.com"
    from-who: "Mr.Foo"
    reply-to: "bar@example.com"
    # 本配置的档案名称为[profile_selfsign]
    mode: "selfsign"
    # 你需要配置 DKIM DNS 记录，这个模式一般用于需要以你自己的域名发件
    # 哪个域名？该域名需要配置相关 DNS 记录，否则邮件会被收件方拒收
    domain: "example.com"
    # DKIM 记录验证的 Selector ，即 selector._domainkey.yourdomain.com
    selector: "default"
    # DKIM 私钥文件，支持 PEM 和 DER 两种格式
    private_key: "/foo/bar/key"

## HTTPServer
http-server:
  ## *是否开启内置 HTTP 服务器
  enabled: true

  ## *监听地址
  host: 0.0.0.0

  ## *监听端口
  port: 8080

  ## *当请求没有对应处理器时是否从本地目录里返回一个文件
  allow-file-transport: true

  ## *允许返回的文件大小，单位KB
  # 可被其它插件修改，一般发生在这个插件自己启动的 HTTP 服务器上
  max-file-size-kb: 20480

  ## *允许的最大URI长度
  # 可被其它插件修改，一般发生在这个插件自己启动的 HTTP 服务器上
  max-uri-length: 2048

  ## *Proxy Protocol
  # 如果你正在使用代理、FRP、内网穿透等工具，你需要根据它们的支持情况设置本字段
  # 可以填入 "v1" | "v2" | "auto" ，其它值均视作不启用
  # * 需要你的代理端也启用本协议！错误配置本协议会导致所有连接不可用。
  proxy-protocol-version: "none"

  ## IP封禁设置
  banip:
    ## 同步游戏内 IP 封禁
    # 开启后，请求会根据游戏内 ban-ip 进行过滤。
    # 禁用此项在低端服务器上可以大幅提升性能。
    sync-game: true

    ## 使用 404 代替 403
    # 开启后，请求因为被封禁而被阻止时会返回 404 ，这可以欺骗客户端资源的存在。
    # 有些端口扫描器可能会根据返回的 4xx 代码标识这个 HTTP 服务器的状态，请自行选择。
    # 如果有人闲得没事干试图通过请求 404/403 页面进行拒绝服务攻击，开启这个选项后将不会构造 403 拒绝消息，在低端服务器上可以节约性能开销。
    use-404-as-403: false

    ## 内置黑名单列表
    # 无论如何始终生效。请不要填写 127.0.0.1 和 0.0.0.0 ，即使你知道你在干什么，我还是要说它们不会按预期工作。
    blacklist:
      - "256.256.256.256"
      - "必须严格匹配IP地址，未来计划增加通配符"
      - "像这种不符合格式的静默忽略"

## 自动更新
update-checker:
  ## *是否启用自动更新检查
  # 频率是每次启动及之后的每天一次
  enabled: true

  ## 自动尝试更新
  # 不推荐，可能导致其它使用本库的插件出现兼容性问题
  auto-download: false

## *是否启用调试模式
# 启用后会输出更多日志信息，建议仅在排查问题时开启
# 该项在预览构建中强制启用
debug: false

## *配置文件版本
version: 5
# 除非在更新配置文件版本，否则请勿修改该值！！！