## HTTPServer
# *本节配置需要重启才能应用修改
http-server:
  ## 是否开启内置 HTTP 服务器
  enabled: true
  ## 监听地址
  host: 0.0.0.0
  ## 监听端口
  port: 8080
  ## 当请求没有对应处理器时是否从本地目录里返回一个文件
  allow-file-transport: true
  ## 允许返回的文件大小，单位KB
  # 可被其它插件修改
  max-file-size-kb: 20480
  ## 允许的最大URI长度
  # 可被其它插件修改
  max-uri-length: 2048

## 自动更新
update-checker:
  ## 是否启用自动更新检查
  # 频率是每次启动及之后的每天一次
  enabled: true
  ## 自动尝试更新
  # 不推荐，可能导致其它使用本库的插件出现兼容性问题
  auto-download: false

## 是否启用调试模式
# 启用后会输出更多日志信息，建议仅在排查问题时开启
debug: false

## 配置文件版本
version: 2
# 除非在更新配置文件版本，否则请勿修改该值！！！