name: StreackLib
version: ${project.version}
build-type: ${build.type}
author: "StreackMC Team"
description: ${project.description}
website: https://github.com/StreackMC/StreackLib
api-version: '1.20.5'
main: com.github.streackmc.StreackLib.self.initializer.forBukkit
load: STARTUP